### ISSUE TITLE
More special functions

### ISSUE THREAD

**Issue by mzalam** [ApproxFun/ApproxFun.jl#116]
Are the bessel functions not supported? I was trying out the very first example, but instead of sin and cosine I am using the besselJ0. The rest of the codes are just copy and paste from the documentation. I get the following error:

`besselj0` has no method matching besselj0(::Fun{UltrasphericalSpace{0},Float64})

Many thanks.

**Comment by MikaelSlevinsky** [comment]
Hi mzalam,

Almost all of Julia's v0.3 [math.jl](https://github.com/JuliaLang/julia/blob/release-0.3/base/math.jl) functions are now supported for `Ultraspherical` spaces. It's far from perfect but it should give you more freedom to explore. The source code for the overrides can be found in [specialfunctions.jl](https://github.com/ApproxFun/ApproxFun.jl/blob/master/src/Extras/specialfunctions.jl) for now, and it follows the same pattern as outlined above by Sheehan: for special functions that have a known differential equation, it is solved via the overridden backslash. Care is taken to ensure the part of the function with largest absolute value is resolved best, while the precision will be as good as possible at the parts with smaller absolute value:

```julia
x = Fun(identity)
f = erf(x)
g = besselj(0,exp(f))
h = airyai(10asin(f)+2g)
```

The functions from number theory, which do not satisfy known simple ODEs, are implemented by the constructor. Since the constructor at this point in time does not have an automatic edge detection algorithm, it will be easy to break these (for instance, `Fun(gamma,[-1.,1.])`).
