### ISSUE TITLE
Fix ProductFun constructor when row/column has size 1

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#153]
example is 

ProductFun(exp(-x^2-y^2),Disk())

**Comment by MikaelSlevinsky** [comment]
This is fixed by @a75477c7a19da4b0dfd6184b0591013983a0ebfa.

There are a couple more issues with `ProductFun` maybe we can go through a little more thoroughly after feat-bivar is merged:

I'm not sure I understand why `ProductFun` is sometimes constructed by a `LowRankFun`. This is lines 57, 84 & 85 in ProductFun.jl.

I don't think chopping in the `ProductFun` constructor by a matrix of coefficients is the right place. The chopping should be specified before that stage in other constructors (and almost always is anyway)

**Comment by dlfivefifty** [comment]
Example was meant to be ProductFun((x,y)->exp(-x^2-y^2),Disk()).  Looks like Mikael fixed this!
