### ISSUE TITLE
Support finite dimensional spaces

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#174]
DiracSpace should really be a finite-dimensional space.  Then the current version would be represented as PiecewiseSpace{DiracSpace,JacobiWeight{Chebyshev}}.  PiecewiseSpace{S<:FiniteSpace,V} would know to just put the finite coefficients first, instead of trying to interlace.

**Comment by dlfivefifty** [comment]
This would also lead to a better PrependColumnsOperator

**Comment by MikaelSlevinsky** [comment]
As far as I can tell, the `DiracSpace` currently stores the centres in the space's `points` and the magnitudes as the first n `coefficients` of the `Fun`.

Alternatively, finite-dimensional spaces could store their coefficients in the space since interlacing is wasteful.

Another alternative is to rejig `SumSpace` to not interlace and have `InterlaceSpace <: SumSpace` for the periodic cases already implemented.

**Comment by MikaelSlevinsky** [comment]
Oh I think I get it now: some algebra is gained for free by having the magnitudes in the coefficients, and there is no way to change the dirac points without changing the space.

**Comment by dlfivefifty** [comment]
Other option is always interlace, just when the # of coefficients are finite, only interlace a finite #

**Comment by dlfivefifty** [comment]
This is related to #88

**Comment by dlfivefifty** [comment]
I've added "dimension" as a starting point, and now SumSPace which used to hardcode ConstantSpace now checks dimension(s)==1.

**Comment by dlfivefifty** [comment]
SumSpace, TupleSPace and PiecewiseSpace now support arbitrary dimensions for their subspaces.
