### ISSUE TITLE
Clenshaw's algorithm

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#190]
is an algorithm on its own. We should be able to template a general routine to evaluate all orthogonal polynomials. Chebfun's [clenshaw algorithm](https://github.com/chebfun/chebfun/blob/development/@chebtech/clenshaw.m) takes a double step (I think it's a specialty of constant coefficient recurrence relations, but I could be wrong) and we should probably implement this if it yields a nontrivial speedup in Julia as well.

**Comment by dlfivefifty** [comment]
Roots also has a general routine.

**Comment by MikaelSlevinsky** [comment]
Inner products are also fast O(min(m,n)) with the orthogonal weight.

**Comment by ajt60gaibb** [comment]
I believe the double step in `chebtech/clenshaw` is because of strangeness with MATLAB performance.  I am not sure it has any mathematical reason behind it.   Nick Hale will know for sure.

BTW, Vanni and I wrote down a generalization "Clenshaw" algorithm for a theoretical rootfinding paper...  http://arxiv.org/abs/1507.00272  So if you ever need Clenshaw's algorithm for nonorthogonal polynomial bases, then the annoying job has been done.

**Comment by MikaelSlevinsky** [comment]
Another related idea is a Clenshaw macro similar to the @horner macro in Julia's base. This would be useful for Funs with coefficients of fixed length. Maybe better than in ApproxFun directly, perhaps in a utility package (or in Julia itself) in case someone needed fast special function approximation that's not built-in.

I used the @horner macro recently for something I was never able to achieve in MATLAB. My [code](https://github.com/MikaelSlevinsky/SincFun.jl/blob/master/src/sinc.jl) for the sine and cosine integrals based on MacLeod's rational approximants is only three times slower than the sine function, or nano-scale pointwise evaluation time.

**Comment by dlfivefifty** [comment]
I think this is done already.
