### ISSUE TITLE
Decide dot/dotu/innerproduct

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#205]
Right now its inconsistent.  One option is add innerproduct(f,g).  The other option is leave dot as innerproduct, and make dotu the other meaning.

**Comment by MikaelSlevinsky** [comment]
`dot{S,T}(f::Vector{S},g::Vector{T})` and `dotu{S,T}(f::Vector{S},g::Vector{T})` should behave the same as when `S` and `T` are numbers. So I support the current implementations.

I think it will be clearer to introduce `innerproduct`, since it isn't necessary to draw analogies to linear algebra for operations.

**Comment by dlfivefifty** [comment]
I wonder if we could get Julia to add support 

⟨f,g⟩

**Comment by dlfivefifty** [comment]
I changed dotu -> bilinearform and dot -> innerproduct
