### ISSUE TITLE
functions with a discontinuity?

### ISSUE THREAD

**Issue by floswald** [ApproxFun/ApproxFun.jl#273]
just wanted to see if you did implement the `splitting` feature of chebfun as well as in this example:

http://www.chebfun.org/examples/approx/NoisyNonsmooth.html

thanks

**Comment by dlfivefifty** [comment]
You can avoid the constructor and then the singularities are found automatically:

ff=x->sign(x-0.1)/2 + cos(4*x);
x=Fun(identity)
f=ff(x)
ApproxFun.plot(f)

Otherwise, you can specify the location of the singularity in the constructor:

f=Fun(ff,[-1.,.1,1.])
ApproxFun.plot(f)

   The ApproxFun constructor is less developed than Chebfun’s, but can usually be avoided (as in the first example).  We don’t have the automatic edge detection yet because of this.

For the “noise”, the following will work soon:

	ff=sign(x-0.1)/2 + cos(4*x) + 1e-8*randn(size(x))
	f=Fun(ff,[-1.,.1,1.];tolerance=1e-8)

It’s just an oversight that the tolerance parameter is not used yet.

**Comment by floswald** [comment]
awesome. 

Can I ask the ignorant question why one needs the noise anyway? I thought chebfun adds it because otherwise it can't handle the problem. looking at your first solution, that doesn't seem to be the case.

**Comment by floswald** [comment]
Heuy @dlfivefifty, one more question. I'm really trying to understand how you do those things, i.e. how do you detect and deal with a discontinuity. The example you post works beautifully. Here is one I can't get to work:

```julia
f2 = x-> min(max(-1,4*(x-0.2)),1)
x = Fun(Interval(-1,1))
f=f2(x)
ApproxFun.plot(f)   # gives me a straight line
Gadfly.plot(f2,-1,1)  # when clearly it's not
```

I realise this is a pathological case, and that's fine. I just wanted to see the polynomial overshooting at the corners to illustrate in a course. however it seems it's cutting them out. Is the formulation of `f2` not in the right format?

**Comment by MikaelSlevinsky** [comment]
Hi Florian,

Your syntax works on development now (Pkg.checkout("ApproxFun","development")):
```julia
julia> using ApproxFun

julia> x = Fun()
Fun([0.0,1.0],Chebyshev(【-1.0,1.0】))

julia> f = min(max(-1,4*(x-0.2)),1)
Fun([-1.0,1.3322676295501878e-16,1.0,-0.0,0.9999999999999997],Chebyshev(【-1.0,-0.04999999999999999】)⨄Chebyshev(【-0.04999999999999999,0.44999999999999996】)⨄Chebyshev(【0.44999999999999996,1.0】))

```

**Comment by dlfivefifty** [comment]
Though "development" is generally very experimental so be careful about updating if you use it.

**Comment by floswald** [comment]
Brilliant! I see you added added `max,min` in `specialfunctions.jl`. That was **fast**, thanks.
