### ISSUE TITLE
Why is LowRankFun hardcoded 69x69 grid?

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#297]

**Comment by MikaelSlevinsky** [comment]
There's a code block that resizes the grid if the first rank-1 approximation isn't resolved by 64,64. (The grid has to start somewhere; chebfun2 starts at 33x33 I think.)

Cheers,

Mikael

**Comment by ajt60gaibb** [comment]
There could/should be a `simplify` at the end of the constructor.

**Comment by MikaelSlevinsky** [comment]
Once the 2D grid size is settled on (either the default 64x64, other user input, or resized in relation to the given function), rank-1 bivariate functions are formed *at* the grid size. This is because the transforms' plans can be computed once and re-used.

Then, before inclusion into the columns and rows of the LowRankFun, they are chopped (Line  122 of LowRankFun.jl on master) with the tolerance of a tenth the global function's tolerance, which is 100eps() times the approximate absolute maximum. This is a form of simplification of rows and columns, but nothing's implemented to simplify by rank.

It's different from chebfun2 since the individual Fun's in the rows and columns don't have to be the same size for better performance I don't think

Hope this helps!

Cheers,

Mikael
