### ISSUE TITLE
Separate out BigFloat FFT

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#304]
This would be useful for other packages, e.g., ToeplitzMatrices.jl

**Comment by dlfivefifty** [comment]
Maybe it should be moved to FastTransforms.jl?@MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
It seems like the relevant Julia issue is https://github.com/JuliaLang/julia/issues/5155 and closed pull request is https://github.com/JuliaLang/julia/pull/6193. It seems like eventually there will be something like an FFTW.jl (sub)module part of a StdLib (set of) package(s).

I don't know exactly what the issue is. Is it that the BigFloat FFT in ApproxFun is useful in ToeplitzMatrices, but it's non-sensical to make ToeplitzMatrices dependent on ApproxFun just for a BigFloat FFT?

It would be nice to have a pure-Julia FFT supporting BigFloat with FFTW1-like code generation available @stevengj.

**Comment by dlfivefifty** [comment]
I just rewrote the BigFloat FFT so that ToeplitzMatrices.jl can work without requiring it, by making the plans <: Base.DCT.Plan, so it's not really a dependancy issue anymore.

It's more to make the functionality available to others without requiring ApproxFun.  FastTransforms.jl seems like a more reasonable home for it.

**Comment by stevengj** [comment]
Maybe SlowTransforms.jl for the BigFloat case?  :wink:
