### ISSUE TITLE
derivative with respect to a Fun

### ISSUE THREAD

**Issue by goretkin** [ApproxFun/ApproxFun.jl#47]
I don't know exactly how to ask this question, but I'd like to try some optimization over `Fun`s.

I found this paper: http://www-m3.ma.tum.de/foswiki/pub/M3/ChebOpt/WebHome/Minimization_of_Variational_Integrals_using_the_Chebfun_System.pdf but I haven't read through it.

I basically would like to try out taking some first-order constrained optimization algorithm (maybe a penalty method) and replace the decision variable vector with an ApproxFun. Does that make sense?

**Comment by MikaelSlevinsky** [comment]
There is a problem and I don't know if it has a quick fix. I'm encountering this while overriding the special functions. The problem is this:

```julia
US = Ultraspherical{0}()
D = Derivative(US,1)
E = Evaluation(US,1.0)
(E*D)[1:10]
rneumann(US)[1:10]
```

The reason these two don't match up is because `D` has a rangespace that's already promoted to `Utraspherical{1}`, while the `rneumann` functional is still in `Ultraspherical{0}`. The latter works correctly with the `Conversion` applied to the hypothetical linear operator below, but the former is already promoted. Maybe what's required is a Derivative functional, which stays in the same space?

**Comment by dlfivefifty** [comment]
This is because there isn’t (yet) a “promotetimes” for TimesFunctional, only TimesOperator.

Sheehan

**Comment by dlfivefifty** [comment]
I think this issue can be closed....
